In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
import matplotlib.pyplot as plt
# Import the API key.
from config import g_key

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("data/WeatherPy_challenge.csv")
city_data_df.head()

,weather,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain(inches),Snow(inches)
0,0,Kormilovka,RU,55.00,74.10,50.00,100,58,4.47,fog,0,0
1,1,New Norfolk,AU,-42.78,147.06,50.00,53,75,11.41,broken clouds,0,0
2,2,Omsukchan,RU,62.53,155.80,36.27,88,100,7.70,overcast clouds,0,0
3,3,Gamba,GA,-2.65,10.00,72.73,85,100,6.73,overcast clouds,0,0
4,4,Luwuk,ID,-0.95,122.79,83.66,58,100,4.41,overcast clouds,0,0

In [3]:
city_data_df.dtypes

weather                  int64
City                    object
Country                 object
Lat                    float64
Lng                    float64
Max Temp               float64
Humidity                 int64
Cloudiness               int64
Wind Speed             float64
Current Description     object
Rain(inches)             int64
Snow(inches)             int64
dtype: object

In [4]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [5]:
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

In [6]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))
rain=input("Do you want it to be raining? (yes/no)")
snow=input("Do you want it to be snowing? (yes/no)")

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 95
Do you want it to be raining? (yes/no)no
Do you want it to be snowing? (yes/no)no

In [7]:
# Filter the dataset to find the cities that fit the criteria.
if (rain=="yes") and (snow=="no"):
    preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & 
                                       (city_data_df["Max Temp"] >= min_temp) &
                                       (city_data_df["Rain(inches)"]>0) &
                                       (city_data_df["Snow(inches)"]==0)]
# Filter the dataset to find the cities that fit the criteria.
elif (snow=="yes") and (rain=="no"):
     preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & 
                                       (city_data_df["Max Temp"] >= min_temp) &
                                       (city_data_df["Snow(inches)"]>0) &
                                       (city_data_df["Rain(inches)"]==0)]
        
# Filter the dataset to find the cities that fit the criteria.
elif (rain=="yes") and (snow=="yes"):
     preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & 
                                       (city_data_df["Max Temp"] >= min_temp) &
                                       (city_data_df["Rain(inches)"]>0) &
                                       (city_data_df["Snow(inches)"]>0)]
elif (rain=="no") and (snow=="no"):
     preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & 
                                       (city_data_df["Max Temp"] >= min_temp) &
                                       (city_data_df["Rain(inches)"]==0) &
                                       (city_data_df["Snow(inches)"]==0)] 
preferred_cities_df.head(10)

,weather,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain(inches),Snow(inches)
4,4,Luwuk,ID,-0.95,122.79,83.66,58,100,4.41,overcast clouds,0,0
20,20,Shieli,KZ,44.17,66.75,76.33,28,0,7.76,clear sky,0,0
21,21,Kahului,US,20.89,-156.47,91.40,49,40,28.86,scattered clouds,0,0
22,22,Hue,VN,16.47,107.60,84.20,74,40,4.70,scattered clouds,0,0
23,23,Port Blair,IN,11.67,92.75,82.47,80,58,9.17,broken clouds,0,0
32,32,Vanimo,PG,-2.67,141.30,78.57,85,91,4.99,moderate rain,0,0
35,35,Butaritari,KI,3.07,172.79,83.34,67,100,8.34,overcast clouds,0,0
36,36,Portland,US,45.52,-122.68,84.00,34,20,8.05,few clouds,0,0
38,38,Langsa,ID,4.47,97.97,78.30,87,0,1.59,clear sky,0,0
43,43,Gashua,NG,12.87,11.05,77.18,76,85,11.41,overcast clouds,0,0

In [8]:
preferred_cities_df.count()

weather                184
City                   184
Country                184
Lat                    184
Lng                    184
Max Temp               184
Humidity               184
Cloudiness             184
Wind Speed             184
Current Description    184
Rain(inches)           184
Snow(inches)           184
dtype: int64

In [9]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

          City Country  Max Temp Current Description    Lat     Lng Hotel Name
4        Luwuk      ID     83.66     overcast clouds  -0.95  122.79
20      Shieli      KZ     76.33           clear sky  44.17   66.75
21     Kahului      US     91.40    scattered clouds  20.89 -156.47
22         Hue      VN     84.20    scattered clouds  16.47  107.60
23  Port Blair      IN     82.47       broken clouds  11.67   92.75
32      Vanimo      PG     78.57       moderate rain  -2.67  141.30
35  Butaritari      KI     83.34     overcast clouds   3.07  172.79
36    Portland      US     84.00          few clouds  45.52 -122.68
38      Langsa      ID     78.30           clear sky   4.47   97.97
43      Gashua      NG     77.18     overcast clouds  12.87   11.05

In [10]:
# Set parameters to search for a hotel.
params = {"radius": 5000,
          "type": "lodging",
          "key": g_key}

In [11]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except IndexError:
        pass
   

info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""    
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [12]:
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
4,Luwuk,ID,83.66,overcast clouds,-0.95,122.79,Hotel Santika Luwuk
20,Shieli,KZ,76.33,clear sky,44.17,66.75,Gostinitsa Aybek Shieli
21,Kahului,US,91.40,scattered clouds,20.89,-156.47,Maui Seaside Hotel
22,Hue,VN,84.20,scattered clouds,16.47,107.60,Saigon Morin Hotel
23,Port Blair,IN,82.47,broken clouds,11.67,92.75,Fortune Resort Bay Island
32,Vanimo,PG,78.57,moderate rain,-2.67,141.30,Vahmoneh Lodge Vanimo
35,Butaritari,KI,83.34,overcast clouds,3.07,172.79,Isles Sunset Lodge
36,Portland,US,84.00,few clouds,45.52,-122.68,Portland Marriott City Center
38,Langsa,ID,78.30,clear sky,4.47,97.97,OYO 2964 Hotel Ridho
43,Gashua,NG,77.18,overcast clouds,12.87,11.05,Forte Oil - Old Lorry Park

In [13]:
# Create the output file (CSV).
output_data_file = "data/WeatherPy_vacation.csv"
# Export the City_Data into a CSV.
hotel_df.to_csv(output_data_file, index_label="hotel")

In [14]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))